/*
 * Copyright 2026 Celiums Solutions LLC
 * Licensed under the Apache License, Version 2.0
 */

// `celiums-cognition setup` — provisions the local Hard stack
// (Postgres + Qdrant + Valkey) via docker compose and waits for health.
//
// Audit P0 #3 (hardcoded credentials): the first run generates a unique
// Postgres password and stores it (chmod 600) in
//   ~/.celiums-cognition/credentials.env
// Subsequent runs reuse the existing file. Compose is invoked with
// `--env-file` so the secret never appears on the command line and the
// process env is otherwise untouched. The plugin's bootstrap fallback
// (plugin-adapter/index.ts) reads the same file before connecting.

import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { existsSync, mkdirSync, readFileSync, writeFileSync, chmodSync } from "node:fs";
import { homedir } from "node:os";
import { randomBytes } from "node:crypto";

const COMPOSE = join(dirname(fileURLToPath(import.meta.url)), "compose", "docker-compose.yml");
const CREDS_DIR = join(homedir(), ".celiums-cognition");
const CREDS_FILE = join(CREDS_DIR, "credentials.env");

function run(cmd: string, args: string[]): number {
  const r = spawnSync(cmd, args, { stdio: "inherit" });
  return r.status ?? 1;
}

/** Ensure ~/.celiums-cognition/credentials.env exists with a unique
 *  Postgres password. Returns the path so the caller can pass it to
 *  `docker compose --env-file`. Idempotent: existing file is left
 *  untouched (the operator's stack keeps the password it was initdb'd
 *  with). */
export function ensureCredentials(): string {
  if (!existsSync(CREDS_DIR)) {
    mkdirSync(CREDS_DIR, { recursive: true, mode: 0o700 });
  }
  if (existsSync(CREDS_FILE)) {
    // Sanity warn if the operator manually downgraded to the legacy
    // default — they should rotate.
    try {
      const txt = readFileSync(CREDS_FILE, "utf8");
      if (/POSTGRES_PASSWORD=celiums$/m.test(txt)) {
        console.warn(
          "[celiums-cognition] WARNING: credentials.env contains the legacy default password " +
          "`celiums`. Rotate via ALTER USER + update credentials.env before exposing this host.",
        );
      }
    } catch { /* unreadable — proceed, compose will surface the error */ }
    return CREDS_FILE;
  }
  // First install — mint a unique password. 32 bytes hex = 256-bit entropy,
  // ASCII-safe so it survives a docker compose env round-trip.
  const password = randomBytes(32).toString("hex");
  const content =
    `# Generated by celiums-cognition setup on ${new Date().toISOString()}.\n` +
    `# DO NOT commit this file. It is read by docker compose (--env-file)\n` +
    `# and by the plugin's bootstrap path. Rotate by ALTER USER + edit.\n` +
    `POSTGRES_USER=celiums\n` +
    `POSTGRES_PASSWORD=${password}\n` +
    `POSTGRES_DB=celiums_memory\n`;
  writeFileSync(CREDS_FILE, content, { mode: 0o600 });
  chmodSync(CREDS_FILE, 0o600);
  console.log(`[celiums-cognition] Generated unique Postgres credentials at ${CREDS_FILE} (mode 600).`);
  return CREDS_FILE;
}

export async function setup(): Promise<number> {
  // Prefer `docker compose` (v2); fall back to `docker-compose` (v1).
  const probe = spawnSync("docker", ["compose", "version"], { stdio: "ignore" });
  if (probe.status !== 0) {
    console.error(
      "[celiums-cognition] Docker (with `docker compose`) is required for the Hard edition.\n" +
        "Install Docker/OrbStack, or use @celiumsai/cognition-lite (zero infra).",
    );
    return 1;
  }

  const credsFile = ensureCredentials();
  const composeArgs = [
    "compose",
    "--env-file", credsFile,
    "-f", COMPOSE,
    "up", "-d", "--wait",
  ];

  console.log(`[celiums-cognition] Provisioning local stack via ${COMPOSE}`);
  console.log("[celiums-cognition] First run pulls images (~60-90s).");
  const code = run("docker", composeArgs);
  if (code !== 0) {
    console.error("[celiums-cognition] docker compose failed.");
    return code;
  }
  console.log(
    "[celiums-cognition] Stack healthy: Postgres :5432, Qdrant :6333, Valkey :6379.\n" +
      "[celiums-cognition] The plugin will connect on next agent run.",
  );
  return 0;
}

// CLI entry: `node dist/setup.js`
if (import.meta.url === `file://${process.argv[1]}`) {
  setup().then((code) => process.exit(code));
}
